name: methuselah
channels:
  - defaults
  - bioconda
dependencies:
  - python=3.7
  - numpy=1.16.*
  - scipy=1.3.*
  - pandas=0.25.*
  - scikit-learn=0.21.*
  - pytables=3.5.*
  - matplotlib=3.1.*
  - samtools=1.6
