name: methuselah
channels:
  - defaults
  - bioconda
dependencies:
  - matplotlib=3.1.*
  - numpy=1.16.*
  - pandas=0.25.*
  - python=3.7
  - scikit-learn=0.21.*
  - scipy=1.3.*
  - samtools=1.6
  - pip
  - pip:
    - tables==3.5.*
